config/routes.rb
Rails.application.routes.draw do

  resources :auctions, only: [:index, :show, :create, :new] do
    resources :bids, only: [:create, :show]
    resources :favorites, only: [:create, :show, :destroy]
    resources :publish, only: [:create]
  end

  resources :users, only: [:new, :create] do
    resources :favorites, only: [:index, :destroy]
    resources :bids, only: [:index]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end



  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new

    can :bid, Auction do |a|
      a.user != user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord

  has_many :favorites, dependent: :destroy
  has_many :favorited, through: :favorites, source: :user

  has_many :bids, dependent: :destroy
  belongs_to :user

  validates :title, :description, :ends_on, :reserve, presence: true

  before_create do
    self.current_price = 1
  end

  def favorited_by?(user)
    favorites.exists?(user: user)
  end

  def favorite_for(user)
    favorites.find_by(user: user)
  end


  include AASM

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published, :canceled, :reserve_met, :reserve_not_met, :won

    event :publish do
      transitions from: :draft, to: :published
    end

    event :reserve_not_met do
      transitions from: :published, to: :reserve_not_met
    end

    event :cancel do
      transitions from: :reserve_not_met, to: :canceled
    end

    event :reserve_met do
      transitions from: :published, to: :reserve_met
    end

    event :won do
      transitions from: :reserve_met, to: :won
    end
  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user
  validates :auction_id, presence: true
  validates :price, presence: true
  validate :amount_greater

  def amount_greater

    if price.present? &&
        auction.present? &&
        price <= auction.current_price
      errors.add(:price, "of bid must be greater than the auction's current bid! 😡")
    end
  end

  after_commit do
    auction.update_attribute(:current_price, self.price)
    if(self.price > auction.reserve)
      auction.update_attribute(:aasm_state, 'reserve_met')
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_validation :downcase_email

  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_auctions, through: :favorites, source: :auction

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true

  private

  def downcase_email
    self.email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path, alert: 'Please sign in first!' unless user_sign_in?
  end

  def user_sign_in?
    session[:user_id].present?
  end
  helper_method :user_sign_in?

  def current_user
    User.find session[:user_id] if user_sign_in?
  end
  helper_method :current_user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_auction, only: [:show]

  def index
    @auctions = Auction.order(created_at: :DESC)
  end

  def new
    @auction = Auction.new
  end

  def show
    @bid = Bid.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  private

  def find_auction
    @auction = Auction.find params[:id]
  end

  def auction_params
    params.require(:auction).permit(:title, :description, :ends_on, :reserve)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @auctions = @user.bids
  end

  def create
    @auction = Auction.find params[:auction_id]
    bid_params = params.require(:bid).permit(:price)
    @bid = Bid.new bid_params
    @bid.auction = @auction
    @bid.user = current_user

    if cannot? :bid, @auction
      redirect_to auction_path(@auction), alert: 'Cannot bid on your own auction! 😥'
      return
    end

    if @bid.save
      redirect_to auction_path(params[:auction_id])
    else
      render 'auctions/show'
    end

  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  before_action :find_favorite, only: [:destroy]
  before_action :find_auction, only: [:create]

  def index
    @user = User.find params[:user_id]
    @auctions = @user.favorited_auctions
  end

  def create

    favorite = Favorite.new(user: current_user, auction: @auction)

    if favorite.save
      redirect_to auction_path(@auction)
    else
      redirect_to auction_path(@auction)
    end
  end

  def destroy

    if @favorite.destroy
      redirect_to auction_path(@favorite.auction)
      @favorite.destroy ? {notice: 'UnFavorite?'} : {alert: @favorite.errors.full_messages.join(', ') }
    end
  end

  private

  def find_favorite
    @favorite ||= Favorite.find params[:id]
  end

  def find_auction
    @auction ||= Auction.find params[:auction_id]
  end
end

app/controllers/publish_controller.rb
class PublishController < ApplicationController
  before_action :authenticate_user!

  def create
    @auction = Auction.find params[:auction_id]
      if @auction.publish!
        redirect_to @auction, notice: 'Auction is published!'
      else
        redirect_to @auction, notice: "Can't publish auction, already published?"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You've Logged In!"
    else
      flash.now[:alert] = "Something Went Wrong, Please Try Again!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_comfirmation)
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created!'
    else
      render :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/publish_helper.rb
module PublishHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auctions/index.html.erb
<h1>Auctions List</h1>

<% @auctions.each do |auction| %>
  <div class="well">
    <h2><%= link_to auction.title, auction_path(auction) %></h2>
  </div>
<% end %>

app/views/auctions/new.html.erb
<%= @auction.errors.full_messages.join(', ') %>
<%= form_for @auction do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= f.label :ends_on %>
    <%= f.text_field :ends_on, type: 'date'  %>
  </div><br>
  <div class='form-group'>
    <%= f.label :reserve %>
    <%= f.text_field :reserve, class: 'form-control' %>
  </div><br>

  <%= f.submit 'Create Auction', class: 'btn btn-success' %>
<% end %>

app/views/auctions/show.html.erb
<h1 style="font-family: 'Times New Roman'; color: Red;"><%= @auction.title %></h1>
<p style="font-size: 18px;"><strong><%= @auction.description %></strong></p>
<p><strong>End Date: <%= @auction.ends_on %></strong></p>
<p><em><strong>Price: $<%= @auction.reserve %></strong></em></p>

  <% if @auction.may_publish? %>
  <%= link_to 'Publish', auction_publish_index_path(@auction), method: :post %>
 <% end %>

<hr>

<%= @bid.errors.full_messages.join(', ') %>
<%= simple_form_for [@auction, @bid] do |f| %>
  <div>
    <%= f.input_field :price %>
    <%= f.submit 'Bid', class:'btn btn-success' %>
  </div>

<% end %>

<% if @auction.favorited_by?(current_user) %>
  <%= link_to user_favorite_path(current_user, @auction.favorite_for(current_user)), method: :delete do %>
    <i class='glyphicon glyphicon-eye-close'>UnWatch</i>
  <% end %>
<% else %>
  <%= link_to auction_favorites_path(@auction), method: :post do %>
    <i class='glyphicon glyphicon-eye-open'>Watch</i>
  <% end %>
<% end %>

<h4>Previous Bids</h4>
<% @auction.bids.order('created_at desc').each do |bid| %>
<div class="well" style="color:white; font-size: 17px; background-color: teal;">
  <p>$<%= bid.price %> at <%= bid.created_at %> by <%= bid.user.first_name %></p>
</div>
<% end %>

app/views/bids/index.html.erb
<h1>Bids Placed By: <%= @user&.first_name %></h1>

<ul style="list-style: none; padding: 0px;">

<% @auctions.each do |a| %>
  <div class="well" style="font-size: 20px;">
  <li><%= link_to a.auction.title, "/auctions/#{a.auction.id}" %></li>
  </div>
<% end %>

</ul>

app/views/favorites/index.html.erb
<h1>Auctions Watched By: <%= @user&.first_name %></h1>

<ul style="list-style: none; padding: 0px;">

  <% @auctions.each do |auction| %>
  <div class="well" style="font-size: 20px;">
    <li><%= link_to auction.title, auction %></li>
  </div>
  <% end %>

</ul>

app/views/users/new.html.erb
<h1 style='text-align: center;'>Sign Up</h1>

<%= @user.errors.full_messages.join(', ') %>
<%= form_for @user do |f| %>
  <div class='form-group'>
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div><br>
  <%= f.submit 'Sign Up', class: 'btn btn-success' %>
<% end %>

app/views/welcome/index.html.erb
<div class="welcome">
<h1>Welcome to Biddr!</h1>
</div>