config/routes.rb
Rails.application.routes.draw do

  resources :auctions, only: [:index, :show, :create, :new] do
    resources :bids, only: [:create, :show]
    resources :favorites, only: [:create, :show, :destroy]
    resources :publish, only: [:create]
  end

  resources :users, only: [:new, :create] do
    resources :favorites, only: [:index, :destroy]
    resources :bids, only: [:index]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end



  root 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    user ||= User.new

    can :bid, Auction do |a|
      a.user != user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord

  has_many :favorites, dependent: :destroy
  has_many :favorited, through: :favorites, source: :user

  has_many :bids, dependent: :destroy
  belongs_to :user

  validates :title, :description, :ends_on, :reserve, presence: true

  before_create do
    self.current_price = 1
  end

  def favorited_by?(user)
    favorites.exists?(user: user)
  end

  def favorite_for(user)
    favorites.find_by(user: user)
  end


  include AASM

  aasm whiny_transitions: false do
    state :draft, initial: true
    state :published, :canceled, :reserve_met, :reserve_not_met, :won

    event :publish do
      transitions from: :draft, to: :published
    end

    event :reserve_not_met do
      transitions from: :published, to: :reserve_not_met
    end

    event :cancel do
      transitions from: :reserve_not_met, to: :canceled
    end

    event :reserve_met do
      transitions from: :published, to: :reserve_met
    end

    event :won do
      transitions from: :reserve_met, to: :won
    end
  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :user
  validates :auction_id, presence: true
  validates :price, presence: true
  validate :amount_greater

  def amount_greater

    if price.present? &&
        auction.present? &&
        price <= auction.current_price
      errors.add(:price, "of bid must be greater than the auction's current bid! 😡")
    end
  end

  after_commit do
    auction.update_attribute(:current_price, self.price)
    if(self.price > auction.reserve)
      auction.update_attribute(:aasm_state, 'reserve_met')
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :auction
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_validation :downcase_email

  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_auctions, through: :favorites, source: :auction

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true

  private

  def downcase_email
    self.email&.downcase!
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_auction, only: [:show]

  def index
    @auctions = Auction.order(created_at: :DESC)
  end

  def new
    @auction = Auction.new
  end

  def show
    @bid = Bid.new
  end

  def create
    @auction = Auction.new auction_params
    @auction.user = current_user
    if @auction.save
      redirect_to auction_path(@auction)
    else
      render :new
    end
  end

  private

  def find_auction
    @auction = Auction.find params[:id]
  end

  def auction_params
    params.require(:auction).permit(:title, :description, :ends_on, :reserve)
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    @auctions = @user.bids
  end

  def create
    @auction = Auction.find params[:auction_id]
    bid_params = params.require(:bid).permit(:price)
    @bid = Bid.new bid_params
    @bid.auction = @auction
    @bid.user = current_user

    if cannot? :bid, @auction
      redirect_to auction_path(@auction), alert: 'Cannot bid on your own auction! 😥'
      return
    end

    if @bid.save
      redirect_to auction_path(params[:auction_id])
    else
      render 'auctions/show'
    end

  end
end

app/controllers/publish_controller.rb
class PublishController < ApplicationController
  before_action :authenticate_user!

  def create
    @auction = Auction.find params[:auction_id]
      if @auction.publish!
        redirect_to @auction, notice: 'Auction is published!'
      else
        redirect_to @auction, notice: "Can't publish auction, already published?"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "You've Logged In!"
    else
      flash.now[:alert] = "Something Went Wrong, Please Try Again!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged Out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_comfirmation)
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created!'
    else
      render :new
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/publish_helper.rb
module PublishHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biddr!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Biddr</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if user_sign_in? %>
            <% current_user = User.find_by_id session[:user_id] %>
            <li><span style="color: white; position: relative; top: 15px;">&nbsp;&nbsp;&nbsp;Hello, <%= current_user.first_name %>!&nbsp;&nbsp;&nbsp; </li></span>
            <li> <%= link_to 'My Bids', user_bids_path(current_user.id) %> </li>
            <li> <%= link_to 'Watched Auctions', user_favorites_path(current_user.id) %> </li>
            <li> <%= link_to 'Create An Auction', new_auction_path %> </li>
            <li><a href="/sessions" data-method = "delete">Sign Out</a></li>
            <% else %>
            <li><a href="/sessions/new">Log In</a></li>
            <li><a href="/users/new">Sign Up</a></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav bottom-nav">
            <li> <%= link_to 'Auctions List', auctions_path %> </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav><br><br><br>


   <% if flash[:notice] %>
     <div class="flash-notice"><%= flash[:notice] %></div>
   <% elsif flash[:alert] %>
     <div class="flash-alert"><%= flash[:alert] %></div>
   <% end %>

   <%= yield %>

  </body>
</html>